export const ACTIONS = {
  SET_USERS: "SET_USERS",
  SET_USERNAME: "SET_USERNAME",
  SET_IS_SEARCH: "SET_IS_SEARCH",
  SET_IS_NOT_FOUND: "SET_IS_NOT_FOUND",
  SET_IS_FETCHING: "SET_IS_FETCHING",
  SET_REPOS: "SET_REPOS",
  SET_PAGE_NUMBER: "SET_PAGE_NUMBER",
  SET_PAGE_COUNT: "SET_PAGE_COUNT",
  SET_FIRST_ITEM: "SET_FIRST_ITEM",
  SET_LAST_ITEM: "SET_LAST_ITEM",
};
